### ISSUE TITLE
pokemontv doesn't work with NSP forwarder

### ISSUE THREAD

**Issue by JrRadiant** [Slluxx/pokemontv#2]
Unfortunately, program doesn't work with it's NSP forwarder.
[PokemonTV_05D124B58BC30000.zip](https://github.com/Slluxx/pokemontv/files/7861098/PokemonTV_05D124B58BC30000.zip)
NRO path is **/switch/pokemontv/pokemontv.nro**

Switch configuration is:
FW: 13.2.0
Card: FAT32
AMS 1.2.5-master-1019bc54

AMS fatal:
Error Code: 2162-0002 (0x4a2)
Program: 010000000000100A

Dear @Slluxx, is there any way to run it with NSP forwarder?

**Comment by Slluxx** [comment]
> Unfortunately, program doesn't work with it's NSP forwarder.

its forwarder? it doesnt have one. so i assume you created one for it?

**Comment by Slluxx** [comment]
Ive looked into it and it seems like you can not create forwarders that open the webbrowser anymore.
I created forwarders for BrowseNX aswell as AIO-Switch-Updater, which both have the webbrowser feature and both crash.

To me it seems that there is nothing i can do. If you want this issue to be resolved, you need to open an issue about forwarders not working with the webbrowser in Atmospheres GitHub repository.
